# control del manejo de toda la app, vive nuestro rpoyecto en el servidor--- Vive en git hub page

language: node_js
cache: 
  directories:
    - ~/.npm
node_js:
  '12'
git:
  depth: 3 
script:
  yarn build
deploy: 
  provider: pages
  edge: true,
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/ 
  target_branch: gh-pages
  commit_message: "Deply Release"
  on:
    branch: master
